# runtime: python312
env: flex
runtime_config:
  runtime_version: "3.12"      # Or the latest supported version

entrypoint: streamlit run streamlit_app.py --browser.serverAddress 0.0.0.0 --server.paport 8080