# app.yaml
# runtime: python312 # Or python310, python312, etc.
instance_class: F2   # A basic instance class, can be scaled up if needed


# The entrypoint is the command to start your Streamlit app.
# - We must tell Streamlit to run on the port provided by App Engine ($PORT).
# - We disable CORS and XSRF protection, as App Engine handles this.
# entrypoint: streamlit run streamlit_app.py --server.port $PORT --server.enableCORS false --server.enableXsrfProtection false
entrypoint: streamlit run streamlit_app.py --server.port=8080 --server.address=0.0.0.0 --server.enableCORS=false --server.enableWebsocketCompression=false --server.enableXsrfProtection=false --server.headless=true

# automatic_scaling:
#   min_instances: 1
#   max_instances: 2
#   target_cpu_utilization: 0.8

runtime: custom
env: flex
